#23 attempt to ripple test error out - stash state

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -99,7 +99,7 @@ script:
       GCP_PROJECT='Travis' BUILD_ID='Travis' PYTHONPATH=cloud/functions/${FUNCTION_NAME}/src:. coverage run --append --source=cloud/functions/${FUNCTION_NAME}/src -m pytest cloud/functions/${FUNCTION_NAME}/tests/
       if [[ $? -ne 0 ]]
       then
-        overall_test_code = $?
+        overall_test_code = 1
         echo
         echo "ERROR - detected tests failed"
         echo
@@ -111,14 +111,19 @@ script:
 
       echo
     done
-      if [[ $? -ne 0 ]]
-      then
-        overall_test_code = $?
-        echo
-        echo "ERROR - detected tests failed, exiting script with failure"
-        echo
-        exit ${overall_test_code}
-      fi
+
+    if [[ $? -ne 0 ]]
+    then
+      overall_test_code = $?
+      echo
+      echo "ERROR - detected tests failed, exiting script with failure"
+      echo
+      exit ${overall_test_code}
+    else
+      echo
+      echo "All tests passed"
+      echo
+    fi
 
 after_success:
   #  look for coverage files
