Port of GCP to Localhost (#16)
* GCP specifics moved to `gcloud` subfolders in `scripts`, `chrono_lens` and `tests` as required
* `localhost` variant added to `chrono_lens` folder
* cloud functions and gcloud code variants now tested where possible via Travis
* common code no longer tested in GCP build as already tested in Travis
* tensorflow version bump c/o dependabot
* refined `README.md` and related READMEs to explain pipeline

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,27 +9,130 @@ matrix:
       dist: xenial
 
 install:
-  - python --version
-  - python -m pip install -U pip
-  #  - python -m easy_install -U setuptools
-  # command to install dependencies\
-  - pip install --use-feature=2020-resolver -r requirements.txt
-  # includes extra 'test' specific dependencies
-  - pip install --use-feature=2020-resolver -r tests/requirements.txt
+  - python3 --version
+  - python3 -m pip install -U pip
 
 script:
+  # NOTE
+  # venv doesn't quite work - neewd to keep "activating" the next venv rather than deactivate first...
+
+  #
+  # --------------- localhost tests ---------------
+  #
+  - echo 'Testing localhost chrono_lens' && echo -en 'travis_fold:start:testing_localhost_chrono_lens\\r'
+  - python3 -m venv localhost-venv
+  - source localhost-venv/bin/activate
+
+  # command to install dependencies
+  - pip install --use-feature=2020-resolver --quiet -r requirements-localhost.txt
+  # includes extra 'test' specific dependencies
+  - pip3 install --use-feature=2020-resolver --quiet -r tests/requirements.txt
   # for codecov support
-  - pip install pytest==4.3.1 pytest-cov==2.9.0
+  - pip3 install --use-feature=2020-resolver --quiet coverage==6.1.2
   # to report installed packages
-  - pip freeze
+  - pip3 freeze
   # command to run tests
-  - PYTHONPATH=.:cloud pytest --cov-config .coveragerc --cov=./ tests/
-  - # Now install requirements for dsc_lib
-  - pip install --use-feature=2020-resolver -r cloud/dsc_lib_tests/requirements.txt
-  - pip freeze
-  - cd cloud/dsc_lib
-  # ...and run the tests on dsc_lib
-  - PYTHONPATH=../..:.. pytest --cov-config .coveragerc --cov=./ ../dsc_lib_tests/
+  - PYTHONPATH=. coverage run --source=. -m pytest tests/
+  - echo -en 'travis_fold:end:testing_localhost_chrono_lens\\r'
+
+
+  #
+  # --------------- gcloud chrono_lens tests ---------------
+  #
+  - echo 'Testing gcloud chrono_lens' && echo -en 'travis_fold:start:testing_gcloud_chrono_lens\\r'
+
+  - python3 -m venv gcloud-venv
+  - source gcloud-venv/bin/activate
+
+  - which python3
+  - which pip3
+  - pip3 -V
+
+  # command to install dependencies
+  - pip3 install --use-feature=2020-resolver --quiet -r requirements-gcloud.txt
+  # includes extra 'test' specific dependencies
+  - pip3 install --use-feature=2020-resolver --quiet -r tests/requirements.txt
+  - pip3 install --use-feature=2020-resolver --quiet -r tests/chrono_lens/gcloud/requirements.txt
+  # for codecov support
+  - pip3 install --use-feature=2020-resolver --quiet coverage==6.1.2
+  # to report installed packages
+  - pip3 freeze
+  # Pretend we're running on GCP
+  - GCP_PROJECT="Travis" BUILD_ID="Travis" PYTHONPATH=. coverage run --append --source=. -m pytest tests/
+
+  - echo -en 'travis_fold:end:testing_gcloud_chrono_lens\\r'
+
+
+  #
+  # --------------- gcloud cloud function tests ---------------
+  #
+
+  - cd cloud/functions
+
+  # Find all subfolders with src, as these are the folders with GCP function code and create ci/cd triggers
+  # Hiding fold keyword in variable to prevent erroneous fold when showing bash code before execution
+  - |
+    overall_test_code=0
+    for repo_dir in **/src/
+    do
+      cd ../..
+      FOLD_SPECIAL_WORD="travis_fold"
+      FUNCTION_NAME=${repo_dir%/*/}
+      echo -en "${FOLD_SPECIAL_WORD}:start:testing_${FUNCTION_NAME}\\\\r"
+      echo
+      echo "Testing cloud function <${FUNCTION_NAME}> locally"
+      python3 -m venv ${FUNCTION_NAME}-venv
+      source ${FUNCTION_NAME}-venv/bin/activate
+
+      pip3 install --use-feature=2020-resolver --quiet -r tests/requirements.txt
+      cd cloud/functions/${FUNCTION_NAME}
+      pip3 install --use-feature=2020-resolver --quiet coverage==6.1.2
+      pip3 install --use-feature=2020-resolver --quiet -r src/requirements.txt
+      if [ -f "tests/requirements.txt" ]; then pip3 install --use-feature=2020-resolver --quiet -r tests/requirements.txt; fi
+
+      cd ../../..
+      pwd
+      echo "GCP_PROJECT='Travis' BUILD_ID='Travis' PYTHONPATH=cloud/functions/${FUNCTION_NAME}/src:. coverage run --append --source=cloud/functions/${FUNCTION_NAME}/src -m pytest cloud/functions/${FUNCTION_NAME}/tests/"
+      GCP_PROJECT='Travis' BUILD_ID='Travis' PYTHONPATH=cloud/functions/${FUNCTION_NAME}/src:. coverage run --append --source=cloud/functions/${FUNCTION_NAME}/src -m pytest cloud/functions/${FUNCTION_NAME}/tests/
+      these_tests_failed=$?
+      if [[ ${these_tests_failed} -ne 0 ]]
+      then
+        overall_test_code=${these_tests_failed}
+        echo
+        echo "ERROR - detected tests failed"
+        echo
+      else
+        echo
+        echo "Detected tests passed"
+        echo
+      fi
+      echo
+      echo "Test failure detected: ${overall_test_code}"
+      echo
+
+      cd cloud/functions
+      echo -en "${FOLD_SPECIAL_WORD}:end:testing_${FUNCTION_NAME}\\\\r"
+      echo
+
+      if [[ ${these_tests_failed} -ne 0 ]]
+      then
+        echo
+        echo "ERROR - detected tests failed, code=${these_tests_failed}"
+        echo
+      fi
+    done
+
+    if [[ ${overall_test_code} -ne 0 ]]
+    then
+      echo
+      echo "ERROR - detected Cloud Function tests failed with code ${overall_test_code}, exiting script with failure"
+      echo
+      exit ${overall_test_code}
+    else
+      echo
+      echo "All Cloud Function tests passed"
+      echo
+    fi
 
 after_success:
   - bash <(curl -s https://codecov.io/bash)
